database:
  sql:
    host: 127.0.0.1
    port: "3306"
    database: prefixes
    username: root
    password: ""
    sample: true

global-prefix:
  - "[global 1]"
  - "[global 2]"
  - "[global 3]"

global-suffix:
  - "[global 1]"
  - "[global 2]"
  - "[global 3]"

global-color:
  - "#ff0000"
  - "#00ff00"
  - "#0000ff"

# blinkohchat.* -- all non-admin commands
# blinkohchat.admin.* -- all admin commands
## blinkohchat.admin.add-global
## blinkohchat.admin.add-personal
## blinkohchat.admin.remove-global
## blinkohchat.admin.remove-personal
## blinkohchat.admin.clear-personal

## blinkohchat.admin.prefix.change-prefix
## blinkohchat.admin.prefix.add-global
## blinkohchat.admin.prefix.add-personal
## blinkohchat.admin.prefix.remove-global
## blinkohchat.admin.prefix.remove-personal
## blinkohchat.admin.prefix.clear-personal

## blinkohchat.admin.suffix.change-prefix
## blinkohchat.admin.suffix.add-global
## blinkohchat.admin.suffix.add-personal
## blinkohchat.admin.suffix.remove-global
## blinkohchat.admin.suffix.remove-personal
## blinkohchat.admin.suffix.clear-personal

## blinkohchat.admin.color.change-color

# blinkohchat.change-prefix

# blinkohchat.prefix.global.1
# blinkohchat.prefix.global.2
# ...
# blinkohchat.prefix.global.*

