name: BlinkohChat
version: '${version}'
main: com.awildboop.blinkohchat.BlinkohChat
api-version: '1.20'
depend: [Vault]
authors: [BOOP]
website: blinkohsmp.com
commands:
  prefix:
    description: Allows you to change your prefix.
permissions:
  change-prefix:
    description: Allows you to change your prefix.